export type Track = {
  id: string;
  title: string;
  artist: string;
  duration: string;
  plays: number;
  size: string;
  category: "instrumental" | "worship";
  imageUrl: string;
  mood?: string;
  featured?: boolean;
  trending?: boolean;
  coverColor: string;
  coverColor2?: string;
  coverImage?: string;
  downloadUrl?: string;
  stationUrl?: string;
};

export type Playlist = {
  id: string;
  title: string;
  curator: string;
  trackCount: number;
  coverColor: string;
};

export type Mood = {
  id: string;
  label: string;
  emoji: string;
  color: string;
  imageUrl?: string;
};

const BASE = "https://shemenmusic.com/three";
const UPL = `${BASE}/wp-content/uploads`;

export const tracks: Track[] = [
  // Featured — The Living Waters Singers
  {
    id: "1",
    title: "Rose Of Sharon",
    artist: "The Living Waters Singers",
    duration: "6:42",
    plays: 1240,
    size: "9.2 MB",
    category: "worship",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2025/11/Rose-Of-Sharon_Inst_NoBVs-mp3-image.webp?fit=768%2C768&ssl=1",
    mood: "anointing",
    featured: true,
    coverColor: "#c2185b",
    coverColor2: "#ad1457",
    coverImage: `${UPL}/2025/11/Rose-Of-Sharon_Inst_NoBVs-mp3-image.webp`,
    stationUrl: `${BASE}/station/rose-of-sharon/`,
    downloadUrl: `${BASE}/station/rose-of-sharon/stream`,
  },
  {
    id: "2",
    title: "No Ordinary Water",
    artist: "The Living Waters Singers",
    duration: "5:18",
    plays: 980,
    size: "7.6 MB",
    category: "instrumental",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2025/11/No-Ordinary-Water_Inst_NoBVs-mp3-image.webp?fit=768%2C768&ssl=1",
    mood: "flow",
    featured: true,
    coverColor: "#0277bd",
    coverColor2: "#01579b",
    coverImage: `${UPL}/2025/11/No-Ordinary-Water_Inst_NoBVs-mp3-image.webp`,
    stationUrl: `${BASE}/station/no-ordinary-water/`,
    downloadUrl: `${BASE}/station/no-ordinary-water/stream`,
  },
  {
    id: "3",
    title: "Living Waters",
    artist: "The Living Waters Singers",
    duration: "7:05",
    plays: 1560,
    size: "10.1 MB",
    category: "worship",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2025/11/living-waters.webp?fit=768%2C768&ssl=1",
    mood: "honour",
    featured: true,
    coverColor: "#00838f",
    coverColor2: "#006064",
    coverImage: `${UPL}/2025/11/jesus-youre-so-cool.webp`,
    stationUrl: `${BASE}/station/jesus-youre-so-cool/`,
    downloadUrl: `${BASE}/station/jesus-youre-so-cool/stream`,
  },
  {
    id: "4",
    title: "Blocked My View Instrumental",
    artist: "First Love Music & Keziah",
    duration: "8:30",
    plays: 2100,
    size: "12.3 MB",
    category: "instrumental",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/arise-mp3-image-scaled.jpg?fit=300%2C300&ssl=1",
    mood: "anointing",
    featured: true,
    coverColor: "#2e7d32",
    coverColor2: "#1b5e20",
    coverImage: `${UPL}/2025/11/ive-found-it.webp`,
    stationUrl: `${BASE}/station/ive-found-it/`,
    downloadUrl: `${BASE}/station/ive-found-it/stream`,
  },
  {
    id: "5",
    title: "He's Waiting",
    artist: "MINISTRY MUSIC INSTRUMENTALS",
    duration: "9:15",
    plays: 870,
    size: "13.4 MB",
    category: "instrumental",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Were-Not-Close-Anymore.jpg?fit=300%2C300&ssl=1",
    mood: "honour",
    trending: true,
    coverColor: "#e64a19",
    coverColor2: "#ff6d00",
    coverImage: `${UPL}/2025/08/i-am-the-way.jpg`,
    stationUrl: `${BASE}/station/i-am-the-way-the-truth-the-life-official-instrumental/`,
    downloadUrl: `${BASE}/station/i-am-the-way-the-truth-the-life-official-instrumental/stream`,
  },
  {
    id: "6",
    title: "Use It Or Lose It 213",
    artist: "Georlynn",
    duration: "4:55",
    plays: 1340,
    size: "7.1 MB",
    category: "worship",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Forsake-The-World.jpg?fit=300%2C300&ssl=1",
    mood: "dancing",
    trending: true,
    coverColor: "#d97706",
  },
  {
    id: "7",
    title: "Jesus, Lord To Me",
    artist: "Alvin Slaughter",
    duration: "6:20",
    plays: 990,
    size: "9.0 MB",
    category: "worship",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Artboard-6-3.png?fit=300%2C300&ssl=1",
    mood: "beloved",
    coverColor: "#6d28d9",
  },
  {
    id: "8",
    title: "I Like The Way You Like Me 148",
    artist: "Georlynn",
    duration: "5:48",
    plays: 1780,
    size: "8.4 MB",
    category: "worship",
    imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/I-Wish.jpg?fit=300%2C300&ssl=1",
    mood: "anointing",
    trending: true,
    coverColor: "#00695c",
    coverColor2: "#004d40",
    coverImage: `${UPL}/2024/04/Jesus-Prayed-31-mp3-image.jpg`,
    stationUrl: `${BASE}/station/jesus-prayed-31/`,
    downloadUrl: `${BASE}/station/jesus-prayed-31/stream`,
  },
  {
    id: "t3",
    title: "Tithes And Offerings 88",
    artist: "First Love Music & Aida",
    duration: "5:24",
    plays: 9200,
    size: "7.8 MB",
    mood: "honour",
    trending: true,
    coverColor: "#8d6e63",
    coverColor2: "#6d4c41",
    coverImage: `${UPL}/2024/08/Tithes-And-Offerings.jpg`,
    stationUrl: `${BASE}/station/tithes-and-offerings-88/`,
    downloadUrl: `${BASE}/station/tithes-and-offerings-88/stream`,
  },
  {
    id: "t4",
    title: "What Is Your Life 16",
    artist: "First Love Music & Aida",
    duration: "4:55",
    plays: 7600,
    size: "7.1 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#e65100",
    coverColor2: "#bf360c",
    coverImage: `${UPL}/2024/08/Artboard-6-3.png`,
    stationUrl: `${BASE}/station/what-is-your-life-16/`,
    downloadUrl: `${BASE}/station/what-is-your-life-16/stream`,
  },
  {
    id: "t5",
    title: "The More I Love, the Less I Be Loved 220",
    artist: "Aseda",
    duration: "6:40",
    plays: 11000,
    size: "9.6 MB",
    mood: "beloved",
    trending: true,
    coverColor: "#ad1457",
    coverColor2: "#880e4f",
    coverImage: `${UPL}/2024/08/The-More-I-Love-the-Less-I-Be-Loved-.jpg`,
    stationUrl: `${BASE}/station/the-more-i-love-the-less-i-be-loved-220/`,
    downloadUrl: `${BASE}/station/the-more-i-love-the-less-i-be-loved-220/stream`,
  },
  {
    id: "t6",
    title: "Lo I Tell You a Mystery 155",
    artist: "First Love Music & Keziah",
    duration: "7:15",
    plays: 8100,
    size: "10.5 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#f9a825",
    coverColor2: "#f57f17",
    coverImage: `${UPL}/2024/08/Lo-I-Tell-You-a-Mystery.jpg`,
    stationUrl: `${BASE}/station/lo-i-tell-you-a-mystery-155/`,
    downloadUrl: `${BASE}/station/lo-i-tell-you-a-mystery-155/stream`,
  },
  {
    id: "t7",
    title: "Soon and Very Soon B",
    artist: "MINISTRY MUSIC INSTRUMENTALS",
    duration: "4:20",
    plays: 6700,
    size: "6.3 MB",
    mood: "honour",
    trending: true,
    coverColor: "#1a237e",
    coverColor2: "#0d1b6e",
    coverImage: `${UPL}/2024/08/Artboard-9-2.png`,
    stationUrl: `${BASE}/station/soon-and-very-soon-b/`,
    downloadUrl: `${BASE}/station/soon-and-very-soon-b/stream`,
  },
  {
    id: "t8",
    title: "Anoint Me (w/ BGVs)",
    artist: "Georlynn & First Love Music",
    duration: "6:11",
    plays: 9500,
    size: "8.9 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#7b1fa2",
    coverColor2: "#6a1b9a",
    coverImage: `${UPL}/2024/08/Anoint-Me.jpg`,
    stationUrl: `${BASE}/station/anoint-me/`,
    downloadUrl: `${BASE}/station/anoint-me/stream`,
  },
  {
    id: "t9",
    title: "Take Me Back",
    artist: "Andraé Crouch",
    duration: "5:33",
    plays: 14200,
    size: "8.0 MB",
    mood: "beloved",
    trending: true,
    coverColor: "#37474f",
    coverColor2: "#263238",
    coverImage: `${UPL}/2024/08/Artboard-11-2.png`,
    stationUrl: `${BASE}/station/take-me-back/`,
    downloadUrl: `${BASE}/station/take-me-back/stream`,
  },
  {
    id: "t10",
    title: "Let Me Love 183",
    artist: "Keziah & First Love Music",
    duration: "5:48",
    plays: 7300,
    size: "8.4 MB",
    mood: "beloved",
    trending: true,
    coverColor: "#558b2f",
    coverColor2: "#33691e",
    coverImage: `${UPL}/2024/08/Let-Me-Love.jpg`,
    stationUrl: `${BASE}/station/let-me-love-183/`,
    downloadUrl: `${BASE}/station/let-me-love-183/stream`,
  },
  {
    id: "t11",
    title: "Go Somewhere 04",
    artist: "First Love Music & Aida",
    duration: "4:10",
    plays: 6200,
    size: "6.0 MB",
    mood: "dancing",
    trending: true,
    coverColor: "#00838f",
    coverColor2: "#006064",
    coverImage: `${UPL}/2024/08/Artboard-17-3.png`,
    stationUrl: `${BASE}/station/go-somewhere-04/`,
    downloadUrl: `${BASE}/station/go-somewhere-04/stream`,
  },
  {
    id: "t12",
    title: "Hallowed Be Thy Name",
    artist: "Clint Brown",
    duration: "7:45",
    plays: 15800,
    size: "11.2 MB",
    mood: "honour",
    trending: true,
    coverColor: "#4527a0",
    coverColor2: "#311b92",
    coverImage: `${UPL}/2024/03/ShemenMUSIC-Clint-Brown-Hallowed-Be-Thy-Name-mp3-image.jpg`,
    stationUrl: `${BASE}/station/hallowed-be-thy-name/`,
    downloadUrl: `${BASE}/station/hallowed-be-thy-name/stream`,
  },
  {
    id: "t13",
    title: "It's Our Time",
    artist: "MINISTRY MUSIC INSTRUMENTALS",
    duration: "5:05",
    plays: 5900,
    size: "7.3 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#c62828",
    coverColor2: "#b71c1c",
    coverImage: `${UPL}/2024/08/Artboard-8-1.png`,
    stationUrl: `${BASE}/station/its-our-time/`,
    downloadUrl: `${BASE}/station/its-our-time/stream`,
  },
  {
    id: "t14",
    title: "If Heaven Never Was Promised",
    artist: "Andraé Crouch",
    duration: "6:22",
    plays: 18600,
    size: "9.2 MB",
    mood: "honour",
    trending: true,
    coverColor: "#1565c0",
    coverColor2: "#0d47a1",
    stationUrl: `${BASE}/station/if-heaven-never-was-promised/`,
    downloadUrl: `${BASE}/station/if-heaven-never-was-promised/stream`,
  },
  {
    id: "t15",
    title: "I Believe In Jesus",
    artist: "Tommy Walker",
    duration: "4:50",
    plays: 11300,
    size: "7.0 MB",
    mood: "honour",
    trending: true,
    coverColor: "#2e7d32",
    coverColor2: "#1b5e20",
    coverImage: `${UPL}/2024/08/i-believe-i-believe-mp3-image-scaled.jpg`,
    stationUrl: `${BASE}/station/i-believe-in-jesus/`,
    downloadUrl: `${UPL}/2024/08/i-believe-i-believe.mp3`,
  },
  {
    id: "t16",
    title: "Loyalty And Disloyalty 100",
    artist: "First Love Music & Aida",
    duration: "6:55",
    plays: 7800,
    size: "10.0 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#4e342e",
    coverColor2: "#3e2723",
    coverImage: `${UPL}/2024/08/Loyalty-And-Disloyalty.jpg`,
    stationUrl: `${BASE}/station/loyalty-and-disloyalty-100/`,
    downloadUrl: `${BASE}/station/loyalty-and-disloyalty-100/stream`,
  },
  {
    id: "t17",
    title: "The Mountain Of the Lord's House 77",
    artist: "First Love Music & Aida",
    duration: "8:30",
    plays: 8400,
    size: "12.3 MB",
    mood: "honour",
    trending: true,
    coverColor: "#0277bd",
    coverColor2: "#01579b",
    coverImage: `${UPL}/2024/08/The-Mountain-Of-the-Lords-House.jpg`,
    stationUrl: `${BASE}/station/the-mountain-of-the-lords-house-77/`,
    downloadUrl: `${BASE}/station/the-mountain-of-the-lords-house-77/stream`,
  },
  {
    id: "t18",
    title: "Blocked My View Instrumental (Official Instrumental)",
    artist: "First Love Music & Keziah",
    duration: "5:18",
    plays: 6600,
    size: "7.6 MB",
    mood: "flow",
    trending: true,
    coverColor: "#00600f",
    coverColor2: "#1b5e20",
    coverImage: `${UPL}/2024/03/blockedmyview-2.png`,
    stationUrl: `${BASE}/station/blocked-my-view-instrumental-with-bvs-official-instrumental/`,
    downloadUrl: `${UPL}/2024/03/Blocked-My-View-Instrumental-with-BVs-Official-Instrumental-1.mp3`,
  },
  {
    id: "t19",
    title: "Shepherd The People",
    artist: "First Love Music",
    duration: "7:08",
    plays: 9100,
    size: "10.3 MB",
    mood: "anointing",
    trending: true,
    coverColor: "#827717",
    coverColor2: "#f9a825",
    coverImage: `${UPL}/2025/01/Shepherd-The-People.jpeg`,
    stationUrl: `${BASE}/station/shepherd-the-people_nov7inst/`,
    downloadUrl: `${UPL}/2025/01/Shepherd-The-People.mp3`,
  },
  {
    id: "t20",
    title: "Jesus You're So Cool",
    artist: "The Living Waters Singers",
    duration: "4:48",
    plays: 5300,
    size: "6.9 MB",
    mood: "honour",
    trending: true,
    coverColor: "#00838f",
    coverColor2: "#006064",
    coverImage: `${UPL}/2025/11/jesus-youre-so-cool.webp`,
    stationUrl: `${BASE}/station/jesus-youre-so-cool/`,
    downloadUrl: `${BASE}/station/jesus-youre-so-cool/stream`,
  },
];

export const playlists: Playlist[] = [
  {
    id: "p1",
    title: "Songs about the Anointing",
    curator: "First Love Music",
    trackCount: 14,
    coverColor: "#7b1fa2",
  },
];

export const moods: Mood[] = [
  { id: "anointing", label: "Anointing", emoji: "🕊️", color: "#d6bd38", imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Artboard-17-6.png?resize=1080%2C1080&ssl=1" },
  { id: "beloved", label: "Belovedosing", emoji: "💛", color: "#d8dde2" },
  { id: "dancing", label: "Dancing", emoji: "🕺", color: "#5d91dd", imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Artboard-19-6.png?resize=1080%2C1080&ssl=1" },
  { id: "flow", label: "FLOW", emoji: "🌊", color: "#d8dde2" },
  { id: "honour", label: "Honour", emoji: "👑", color: "#8aa2bd", imageUrl: "https://i0.wp.com/shemenmusic.com/three/wp-content/uploads/2024/08/Artboard-21-4.png?resize=1080%2C1080&ssl=1" },
];

export function formatPlays(n: number): string {
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}

export function totalDuration(trackList: Track[]): string {
  const minutes = trackList.reduce((sum, track) => {
    const [m, s] = track.duration.split(":").map(Number);
    return sum + m + s / 60;
  }, 0);

  if (minutes >= 60) {
    const hours = Math.floor(minutes / 60);
    const remaining = Math.round(minutes % 60);
    return `${hours}h ${remaining}m`;
  }

  return `${Math.round(minutes)}m`;
}
