/**
 * Matches lyrics .txt files to track IDs, copies them as .lrc to public/lyrics/,
 * and writes lib/lyrics-map.ts with the trackId → filename mapping.
 */
import fs from "fs";
import path from "path";

const LYRICS_SRC = "/Users/bennymillsthompson/Downloads/lyrics_extracted/lyrics for Benny";
const LYRICS_DEST = "/Users/bennymillsthompson/Downloads/shemen-music/public/lyrics";
const DATA_FILE = "/Users/bennymillsthompson/Downloads/shemen-music/lib/data.ts";
const MAP_OUT = "/Users/bennymillsthompson/Downloads/shemen-music/lib/lyrics-map.ts";

// Normalize a string for fuzzy matching
function norm(str) {
  return str
    .toLowerCase()
    .replace(/\(official instrumental.*?\)/gi, "")
    .replace(/\(instrumental.*?\)/gi, "")
    .replace(/\(with bvs.*?\)/gi, "")
    .replace(/\(.*?\)/g, "")          // remove any remaining parens
    .replace(/\s+\d+\s*$/, "")        // strip trailing numbers like " 194"
    .replace(/^\d+\.\s*/, "")         // strip leading "67. "
    .replace(/[^a-z0-9\s]/g, " ")     // remove punctuation
    .replace(/\s+/g, " ")
    .trim();
}

// Extract all track {id, title} from data.ts
const dataSource = fs.readFileSync(DATA_FILE, "utf8");
const trackPairs = [];
const idMatches = [...dataSource.matchAll(/id:\s*"([^"]+)"/g)];
const titleMatches = [...dataSource.matchAll(/title:\s*"([^"]+)"/g)];
// Skip first 3 matches which are type definitions
for (let i = 3; i < idMatches.length; i++) {
  const id = idMatches[i][1];
  const title = titleMatches[i] ? titleMatches[i][1] : "";
  trackPairs.push({ id, title, normTitle: norm(title) });
}
console.log(`Loaded ${trackPairs.length} tracks`);

// Read all lyrics files
const lyricsFiles = fs.readdirSync(LYRICS_SRC).filter(f => f.endsWith(".txt"));
console.log(`Found ${lyricsFiles.length} lyrics files`);

const mapping = {}; // trackId → lrc filename (without path)
const used = new Set();

for (const file of lyricsFiles) {
  const normFile = norm(file.replace(/\.txt$/, ""));

  // Find best matching track
  let bestId = null;
  let bestScore = 0;

  for (const track of trackPairs) {
    if (used.has(track.id)) continue;
    const score = similarity(normFile, track.normTitle);
    if (score > bestScore) {
      bestScore = score;
      bestId = track.id;
    }
  }

  if (bestId && bestScore >= 0.72) {
    const slug = bestId + ".lrc";
    // Copy and clean up the file
    const raw = fs.readFileSync(path.join(LYRICS_SRC, file), "utf8");
    const cleaned = cleanLrc(raw);
    fs.writeFileSync(path.join(LYRICS_DEST, slug), cleaned, "utf8");
    mapping[bestId] = slug;
    used.add(bestId);
    console.log(`✓ [${bestScore.toFixed(2)}] "${file}" → ${bestId}`);
  } else {
    console.log(`✗ [${bestScore.toFixed(2)}] "${file}" — no match`);
  }
}

console.log(`\nMatched ${Object.keys(mapping).length} / ${lyricsFiles.length} files`);

// Write the mapping module
const lines = Object.entries(mapping)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, file]) => `  "${id}": "${file}",`);

const output = `// Auto-generated by scripts/build-lyrics.mjs — do not edit manually
export const lyricsMap: Record<string, string> = {
${lines.join("\n")}
};
`;
fs.writeFileSync(MAP_OUT, output, "utf8");
console.log(`\nWrote ${MAP_OUT}`);

// ── helpers ────────────────────────────────────────────────────────────────

function similarity(a, b) {
  if (a === b) return 1;
  // Word overlap (Jaccard)
  const wa = new Set(a.split(" ").filter(Boolean));
  const wb = new Set(b.split(" ").filter(Boolean));
  const inter = [...wa].filter(w => wb.has(w)).length;
  const union = new Set([...wa, ...wb]).size;
  return union === 0 ? 0 : inter / union;
}

function cleanLrc(raw) {
  const lines = raw.split("\n");
  const out = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    // Strip lines that are just a title or BPM number at the top (no bracket)
    if (out.length === 0 && !trimmed.startsWith("[")) continue;
    // Remove double-timestamp like [01:01.52][00:41.27]text → keep first
    const cleaned = trimmed.replace(/(\[\d+:\d+\.\d+\])\[\d+:\d+\.\d+\]/g, "$1");
    out.push(cleaned);
  }
  return out.join("\n") + "\n";
}
